### ISSUE TITLE
edit counter: problem displaying top edits when article title starts with a number

### ISSUE THREAD

**Issue by Grahamwp** [x-tools/xtools-legacy#39]
The results for my most frequently edited pages in [X! Edit Counter](https://tools.wmflabs.org/xtools/pcount/index.php?name=Graham87&lang=en&wiki=wikipedia) contain two values in the main namespace, "0" and "1". Comparing this with the [output of the the user analysis tool](https://tools.wmflabs.org/supercount/index.php?user=Graham87&project=en.wikipedia&toplimit=10), it becomes clear that these two articles that I've edited the most frequently are actually 1972 and 1959, respectively.

**Comment by Hedonil** [comment]
Woo! The result array from database was ok.
[Swimming_pool] => 332
[Netball] => 247
[1972] => 240
[Civil_engineering] => 237
[List_of_French_people] => 228
[Tom_Jones_(singer)] => 185
[Dust_Bowl] => 178
[Diving] => 175
[Bumblebee] => 166
[1959] => 164

Turned out the culprit was an  "array_reverse( $articles )" in output-formatting. 
Eliminated w/ fire. Thanks.
