### ISSUE TITLE
User not found for project=www.mediawiki.org

### ISSUE THREAD

**Issue by numbermaniac** [x-tools/xtools-legacy#85]
https://tools.wmflabs.org/xtools-ec/?user=Numbermaniac&project=www.mediawiki.org

It just insists I don't exist, even if I change the end to mediawikiwiki. Why?

**Comment by ricordisamoa** [comment]
No one exists on www.mediawiki.org :smiley:

**Comment by Krinkle** [comment]
I debugged it from my personal account and learned the following so far.
- The url parameters are interpreted fine. Contrary to comments in #93, the initial call to `WebTool:: getWikiInfo()` that reads project from `$wgRequest` is not the problem. The `preg_match( '/(?:wiki$|wikipedia)/'` if condition is not reached in case of `project=www.mediawiki.org`.

Logging `$wt->wikiInfo` after [index.php:46](https://github.com/x-tools/xtools/blob/c49a5e3d/public_html/ec/index.php#L46) yields the following:

```
{
  ["lang"]=>
  string(3) "www"
  ["wiki"]=>
  string(9) "mediawiki"
  ["domain"]=>
  string(17) "www.mediawiki.org"
  ["database"]=>
  string(13) "mediawikiwiki"
```

So far so good. Then, it calls `WebTool::getUserInfo()`, which does the following on [WebTool.php:440](https://github.com/x-tools/xtools/blob/c49a5e3db99b941393564a0a2f6a37c0e7d49f34/modules/WebTool.php#L440-L443):

``` php
      if ( !$lang || !$wiki ){
         $wi = $this->wikiInfo;
            $lang = $wi->lang; // "www"
            $wiki = $wi->wiki; // "mediawiki"
      }

/* ... */
  $dbr2 = $this->loadDatabase( $lang, $wiki );
```

Then, WebTool::loadDatabase calls getWikiInfo, **again** ([WebTool.php:616](https://github.com/x-tools/xtools/blob/c49a5e3db99b941393564a0a2f6a37c0e7d49f34/modules/WebTool.php#L616)):

``` php
$wi = $this->getWikiInfo( $lang, $wiki);
         $server = $wi->database.".labsdb";
         $dbname = $wi->database."_p";
```

This is where it goes wrong. Instead of re-using the object we already got, it tries to get a new WikiInfo object using only the language and wiki portion, which doesn't work and produces the following:

```
{
  ["lang"]=>
  bool(false)
  ["wiki"]=>
  string(9) "wikipedia"
  ["domain"]=>
  NULL
  ["database"]=>
  NULL
```

After this the database will yield a null result when the tool tries to query the user edit count etc.

Either we need to change `getWikiInfo()` to support finding www.mediawiki.org when given lang=www wiki=mediawiki. Or we need to change `loadDatabase()` to take a WikiInfo object instead of separate lang/wiki, so that `getUserInfo()` can pass it the object it already has.

**Comment by Matthewrbowker** [comment]
I have made the modifications suggested by @Krinkle.  However, it has broken the multiquery method later in that file, so now we just get a different error message.  I will continue troubleshooting.

**Comment by Matthewrbowker** [comment]
Please try now.  It has been working for me.

**Comment by numbermaniac** [comment]
Looks like it's working for me too. Thanks!
