### ISSUE TITLE
Font size for History statistic for es.wikipedia.org

### ISSUE THREAD

**Issue by Triplecana** [x-tools/xtools-legacy#98]
The size for es.wikipedia.org articles in History statistic tab appears too small. We want to use this tool in es.wiki but we hope if this can be corrected first.

Thank you it is a great app

Triplecaña

**Comment by Matthewrbowker** [comment]
Hi, @Triplecana!  Can you give me an example URL where you're seeing this issue?

**Comment by Triplecana** [comment]
Try with
https://tools.wmflabs.org/xtools-articleinfo/?article=Intempo&project=es.wikipedia.org

Carlos Madrid

On Tue, Jun 28, 2016 at 5:30 PM +0200, "Matthew Bowker" <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi, @Triplecanahttps://github.com/Triplecana! Can you give me an example URL where you're seeing this issue?

##

**Comment by Matthewrbowker** [comment]
Oh wow, definitely a bug.  I'll see what I can do :)

Thank you for reporting!

**Comment by MusikAnimal** [comment]
This made me laugh. What a peculiar bug!

I think it might have something to do with the "page assessment" tool, which fails because this is not an enwiki article. I'm seeing the same behaviour with all wikis other than enwiki. It looks like it's adding `font-size: 90%` to the `<body>` tag.

I also think this page assessment thing is slowing the tool down? All enwiki articles seem to take quite a while to load. Perhaps we should remove it altogether.

**Comment by Matthewrbowker** [comment]
This was fixed by #111, it doesn't appear anymore for me.  Let me know if you have any additional problems!
